# encoding: utf8

LOCATION_TRAFFIC_CONVENIENCE = 'location_traffic_convenience'
LOCATION_DISTANCE_FROM_BUSINESS_DISTRICT = 'location_distance_from_business_district'
LOCATION_EASY_TO_FIND = 'location_easy_to_find'

SERVICE_WAIT_TIME = 'service_wait_time'
SERVICE_WAITERS_ATTITUDE = 'service_waiters_attitude'
SERVICE_PARKING_CONVENIENCE = 'service_parking_convenience'
SERVICE_SERVING_SPEED = 'service_serving_speed'

PRICE_LEVEL = 'price_level'
PRICE_COST_EFFECTIVE = 'price_cost_effective'
PRICE_DISCOUNT = 'price_discount'

ENVIRONMENT_DECORATION = 'environment_decoration'
ENVIRONMENT_NOISE = 'environment_noise'
ENVIRONMENT_SPACE = 'environment_space'
ENVIRONMENT_CLEANESS = 'environment_cleaness'

DISH_PORTION = 'dish_portion'
DISH_TASTE = 'dish_taste'
DISH_LOOK = 'dish_look'

DISH_RECOMMENDATION = 'dish_recommendation'
OTHERS_OVERALL_EXPERIENCE = 'others_overall_experience'
OTHERS_WILLING_TO_CONSUME_AGAIN = 'others_willing_to_consume_again'

COLS = [LOCATION_TRAFFIC_CONVENIENCE, LOCATION_DISTANCE_FROM_BUSINESS_DISTRICT, LOCATION_EASY_TO_FIND,
        SERVICE_WAIT_TIME, SERVICE_WAITERS_ATTITUDE, SERVICE_PARKING_CONVENIENCE, SERVICE_SERVING_SPEED,
        PRICE_LEVEL, PRICE_COST_EFFECTIVE, PRICE_DISCOUNT,
        ENVIRONMENT_DECORATION, ENVIRONMENT_NOISE, ENVIRONMENT_SPACE, ENVIRONMENT_CLEANESS,
        DISH_PORTION, DISH_TASTE, DISH_LOOK, DISH_RECOMMENDATION,
        OTHERS_OVERALL_EXPERIENCE, OTHERS_WILLING_TO_CONSUME_AGAIN]
